version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: trustai_db
    restart: always
    environment:
      POSTGRES_USER: trustai
      POSTGRES_PASSWORD: trustai123
      POSTGRES_DB: trustai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: trustai_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://trustai:trustai123@db:5432/trustai_db
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: llama3.2
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: trustai_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
